### ISSUE TITLE
ValueError: max() arg is an empty sequence

### ISSUE THREAD

**Issue by batuhan3526** [TreborNamor/TradingView_Machine_Learning#7]
Loading script...
script has timed out.
Traceback (most recent call last):
  File "C:\Users\MONSTER\OneDrive\Desktop\strateji\ML ile stop ve take profıt opt\scripts\stoploss_linear.py", line 77, in <module>
    run_script(webdriver.driver)
  File "C:\Users\MONSTER\OneDrive\Desktop\strateji\ML ile stop ve take profıt opt\scripts\stoploss_linear.py", line 42, in run_script
    best_key = find.best_key()
  File "C:\Users\MONSTER\OneDrive\Desktop\strateji\ML ile stop ve take profıt opt\scripts\find.py", line 5, in best_key
    best_in_dict = max(profits, key=profits.get)
ValueError: max() arg is an empty sequence

**Comment by bertinlr** [comment]
Same issue I pointed out here https://github.com/TreborNamor/TradingView_Machine_Learning/issues/6#issuecomment-814284820

**Comment by 0AD0** [comment]
I also get the same issue, even with the latest and greatest :(

**Comment by TreborNamor** [comment]
Sorry for the inconvenience. Tradingview has been updating their website
lately. I just updated the click.py file a few minutes ago. Was this the
one you tried?

**Comment by airqualityanthony** [comment]
this error is still continuing, any chance of an update?
