### ISSUE TITLE
OSError: [Errno 86] Bad CPU type in executable geckodriver

### ISSUE THREAD

**Issue by 0AD0** [TreborNamor/TradingView_Machine_Learning#8]
[WDM] - Driver [/Users/badiead/.wdm/drivers/geckodriver/macos/v0.29.1/geckodriver] found in cache
Traceback (most recent call last):
  File "/Users/badiead/Downloads/TradingView_Machine_Learning-master/scripts/takeprofit_linear.py", line 3, in <module>
    from functions import click, webdriver, show_me, get, find
  File "/Users/badiead/Downloads/TradingView_Machine_Learning-master/functions/click.py", line 6, in <module>
    from functions.webdriver import driver
  File "/Users/badiead/Downloads/TradingView_Machine_Learning-master/functions/webdriver.py", line 18, in <module>
    driver = create_driver()
  File "/Users/badiead/Downloads/TradingView_Machine_Learning-master/functions/webdriver.py", line 14, in create_driver
    driver = webdriver.Firefox(profile, options=options, executable_path=GeckoDriverManager().install())
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/selenium/webdriver/firefox/webdriver.py", line 164, in __init__
    self.service.start()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/selenium/webdriver/common/service.py", line 72, in start
    self.process = subprocess.Popen(cmd, env=self.env,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 1823, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 86] Bad CPU type in executable: '/Users/badiead/.wdm/drivers/geckodriver/macos/v0.29.1/geckodriver'

**Comment by 0AD0** [comment]
The simple fix to this is to install the latest geckodriver in /Users/badiead/.wdm/drivers/geckodriver/macos/v0.29.1/geckodriver
